final Map<String, Map<String, String>> lang = {
  'pt': {
    'menu_title': 'MENU PRINCIPAL',
    'open_folder': 'ABRIR PASTA',
    'library': 'BIBLIOTECA',
    'queue': 'FILA DE ESPERA',
    'equalizer': 'EQUALIZADOR',
    'settings': 'CONFIGURAÇÕES',
    'games': 'JOGOS',
    'lib_empty': 'BIBLIOTECA VAZIA',
    'set_title': 'CONFIGURAÇÕES',
    'set_lang': 'IDIOMA: PT',
    'set_theme': 'TEMA: ',
    'set_visual': 'ESTILO: ',
    'set_focus': 'FOCO: ',
    'set_clear': 'LIMPAR DADOS',
    'set_donate': 'COMPRA-ME UM CAFÉ',
    'vol': 'VOL',
  },
  'en': {
    'menu_title': 'MAIN MENU',
    'open_folder': 'OPEN FOLDER',
    'library': 'LIBRARY',
    'queue': 'QUEUE',
    'equalizer': 'EQUALIZER',
    'settings': 'SETTINGS',
    'games': 'GAMES',
    'lib_empty': 'EMPTY LIBRARY',
    'set_title': 'SETTINGS',
    'set_lang': 'LANGUAGE: EN',
    'set_theme': 'THEME: ',
    'set_visual': 'STYLE: ',
    'set_focus': 'FOCUS: ',
    'set_clear': 'CLEAR DATA',
    'set_donate': 'BUY ME A COFFEE',
    'vol': 'VOL',
  },
};
